name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Build Docker Image
      run: docker build -t ${{ secrets.AWS_REGISTRY_URI }}/your-image-name:latest .

    - name: Authenticate with AWS ECR
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ secrets.AWS_REGION }}

    - name: Push to ECR
      run: docker push ${{ secrets.AWS_REGISTRY_URI }}/your-image-name:latest
